FROM node:18-alpine as builder
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install 
COPY ./ ./
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install --prod 
COPY --from=builder /app/dist ./dist

CMD ["node", "dist/src/main.js"]